### 15/07/024

# Bias:-
   It is simply defined as the inability of the model because of that there is some difference or error occurring between the model's predicted value      and the actual value. These differences between actual or expected values and the predicted values are known as error or bias error or error due to     bais. Bias is a systematic error that occurs due to wrong assumptions in machine learning process.

### Low Bias:-  
   Low bias value means fewer assumption are taken to build the target function. In this case, the model will closely match the training datset.

### High Bias:-
   High bias means more assumption are taken to build that target function. In this case, the model will not match the training dataset closely.

### What is Variance?
   Variance is the measure of spread in data from its means position. In machine learning variance is the amount by hich the performance of a              predictive model changes when it is trained on different subsets of the training data.

### Bias Variance Tradeoff:-
   If the algorithm is too simple (hypothesis with linear equation) then it may be on high bias and low variance condition and thus is error-prone. If     algorithms fit too complex (hypothesis with high degree equation) then it may be in high variance and low bias. In the latter condition, the new        entries will not perform well. Well there is something between both of these conditions, known as Trade-off or Bias Variance Trade-off. This            tradeoff incomplexity is why there is a tradeoff between bais and variance. An algorithm can't be more conplex and less complex at the same time.       For the graph, the perfect tradeoff will be like this. The high-bias model will not be able to copture the dataset trend. It is considered as the       underfitting model which has a high error rate. It is due to a very siplified algorithm.

### Underfitting in Machine Learning:-
   A statistical model or a machine learning algorithm is said to have underfitting when a model is too simple to capture data complexities.

# 18/07/024

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
%matplotlib inline
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv('heart_disease_1.csv')
df

,age,sex,Chest Pain Type,trestbps,chol,fbs,cardio_result,max_heartrate,exercise_angina,ST_depression,slope,no_majorvessel(0-3),thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
df.describe()

,age,sex,Chest Pain Type,trestbps,chol,fbs,cardio_result,max_heartrate,exercise_angina,ST_depression,slope,no_majorvessel(0-3),thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [4]:
df.dtypes

age                      int64
sex                      int64
Chest Pain Type          int64
trestbps                 int64
chol                     int64
fbs                      int64
cardio_result            int64
max_heartrate            int64
exercise_angina          int64
ST_depression          float64
slope                    int64
no_majorvessel(0-3)      int64
thal                     int64
target                   int64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  303 non-null    int64
 1   sex                  303 non-null    int64
 2   Chest Pain Type      303 non-null    int64
 3   trestbps             303 non-null    int64
 4   chol                 303 non-null    int64
 5   fbs                  303 non-null    int64
 6   cardio_result        303 non-null    int64
 7   max_heartrate        303 non-null    int64
 8   exercise_angina      303 non-null    int64
 9   ST_depression        303 non-null    float64
 10  slope                303 non-null    int64
 11  no_majorvessel(0-3)  303 non-null    int64
 12  thal                 303 non-null    int64
 13  target               303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:
df.head()

,age,sex,Chest Pain Type,trestbps,chol,fbs,cardio_result,max_heartrate,exercise_angina,ST_depression,slope,no_majorvessel(0-3),thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [7]:
df.isna().sum()

age                    0
sex                    0
Chest Pain Type        0
trestbps               0
chol                   0
fbs                    0
cardio_result          0
max_heartrate          0
exercise_angina        0
ST_depression          0
slope                  0
no_majorvessel(0-3)    0
thal                   0
target                 0
dtype: int64

In [8]:
df.target.value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [9]:
x=df.drop('target',axis=1)

In [10]:
y=df['target']

In [28]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2)

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
model= RandomForestClassifier(n_estimators=100)

In [38]:
model.score(x_test,y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0.
 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1.
 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.
 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1.
 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1.
 1. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
model.score(x_test,y_test)

In [ ]:
model.fit(x_train,y_test)

In [ ]:
model.score(x_test,y_test)